// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"




# 11 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | String of (string)
  | Ident of (string)
  | Delete
  | Kill
  | Resolve
  | Declare
  | Sub
  | Add
  | Print
  | Set
  | Quit
  | QuestionMark
  | CloseParen
  | OpenParen
  | Comma
  | Disadvantage
  | Advantage
  | Max
  | Min
  | Dot
  | Minus
  | Plus
  | DSymbol
  | Number of (int)
  | EOF
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_String
    | TOKEN_Ident
    | TOKEN_Delete
    | TOKEN_Kill
    | TOKEN_Resolve
    | TOKEN_Declare
    | TOKEN_Sub
    | TOKEN_Add
    | TOKEN_Print
    | TOKEN_Set
    | TOKEN_Quit
    | TOKEN_QuestionMark
    | TOKEN_CloseParen
    | TOKEN_OpenParen
    | TOKEN_Comma
    | TOKEN_Disadvantage
    | TOKEN_Advantage
    | TOKEN_Max
    | TOKEN_Min
    | TOKEN_Dot
    | TOKEN_Minus
    | TOKEN_Plus
    | TOKEN_DSymbol
    | TOKEN_Number
    | TOKEN_EOF
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_Command
    | NONTERM_SetValue
    | NONTERM_Idents
    | NONTERM_PrintValue
    | NONTERM_MultiRoll
    | NONTERM_MaybeTest
    | NONTERM_Roll
    | NONTERM_RollList
    | NONTERM_PlusList
    | NONTERM_SimpleRoll

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | String _ -> 0 
  | Ident _ -> 1 
  | Delete  -> 2 
  | Kill  -> 3 
  | Resolve  -> 4 
  | Declare  -> 5 
  | Sub  -> 6 
  | Add  -> 7 
  | Print  -> 8 
  | Set  -> 9 
  | Quit  -> 10 
  | QuestionMark  -> 11 
  | CloseParen  -> 12 
  | OpenParen  -> 13 
  | Comma  -> 14 
  | Disadvantage  -> 15 
  | Advantage  -> 16 
  | Max  -> 17 
  | Min  -> 18 
  | Dot  -> 19 
  | Minus  -> 20 
  | Plus  -> 21 
  | DSymbol  -> 22 
  | Number _ -> 23 
  | EOF  -> 24 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_String 
  | 1 -> TOKEN_Ident 
  | 2 -> TOKEN_Delete 
  | 3 -> TOKEN_Kill 
  | 4 -> TOKEN_Resolve 
  | 5 -> TOKEN_Declare 
  | 6 -> TOKEN_Sub 
  | 7 -> TOKEN_Add 
  | 8 -> TOKEN_Print 
  | 9 -> TOKEN_Set 
  | 10 -> TOKEN_Quit 
  | 11 -> TOKEN_QuestionMark 
  | 12 -> TOKEN_CloseParen 
  | 13 -> TOKEN_OpenParen 
  | 14 -> TOKEN_Comma 
  | 15 -> TOKEN_Disadvantage 
  | 16 -> TOKEN_Advantage 
  | 17 -> TOKEN_Max 
  | 18 -> TOKEN_Min 
  | 19 -> TOKEN_Dot 
  | 20 -> TOKEN_Minus 
  | 21 -> TOKEN_Plus 
  | 22 -> TOKEN_DSymbol 
  | 23 -> TOKEN_Number 
  | 24 -> TOKEN_EOF 
  | 27 -> TOKEN_end_of_input
  | 25 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_Command 
    | 3 -> NONTERM_Command 
    | 4 -> NONTERM_Command 
    | 5 -> NONTERM_Command 
    | 6 -> NONTERM_Command 
    | 7 -> NONTERM_Command 
    | 8 -> NONTERM_Command 
    | 9 -> NONTERM_Command 
    | 10 -> NONTERM_Command 
    | 11 -> NONTERM_Command 
    | 12 -> NONTERM_SetValue 
    | 13 -> NONTERM_SetValue 
    | 14 -> NONTERM_SetValue 
    | 15 -> NONTERM_SetValue 
    | 16 -> NONTERM_SetValue 
    | 17 -> NONTERM_SetValue 
    | 18 -> NONTERM_SetValue 
    | 19 -> NONTERM_SetValue 
    | 20 -> NONTERM_SetValue 
    | 21 -> NONTERM_SetValue 
    | 22 -> NONTERM_Idents 
    | 23 -> NONTERM_Idents 
    | 24 -> NONTERM_PrintValue 
    | 25 -> NONTERM_PrintValue 
    | 26 -> NONTERM_MultiRoll 
    | 27 -> NONTERM_MultiRoll 
    | 28 -> NONTERM_MaybeTest 
    | 29 -> NONTERM_MaybeTest 
    | 30 -> NONTERM_MaybeTest 
    | 31 -> NONTERM_Roll 
    | 32 -> NONTERM_Roll 
    | 33 -> NONTERM_Roll 
    | 34 -> NONTERM_RollList 
    | 35 -> NONTERM_RollList 
    | 36 -> NONTERM_PlusList 
    | 37 -> NONTERM_PlusList 
    | 38 -> NONTERM_PlusList 
    | 39 -> NONTERM_SimpleRoll 
    | 40 -> NONTERM_SimpleRoll 
    | 41 -> NONTERM_SimpleRoll 
    | 42 -> NONTERM_SimpleRoll 
    | 43 -> NONTERM_SimpleRoll 
    | 44 -> NONTERM_SimpleRoll 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 27 
let _fsyacc_tagOfErrorTerminal = 25

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | String _ -> "String" 
  | Ident _ -> "Ident" 
  | Delete  -> "Delete" 
  | Kill  -> "Kill" 
  | Resolve  -> "Resolve" 
  | Declare  -> "Declare" 
  | Sub  -> "Sub" 
  | Add  -> "Add" 
  | Print  -> "Print" 
  | Set  -> "Set" 
  | Quit  -> "Quit" 
  | QuestionMark  -> "QuestionMark" 
  | CloseParen  -> "CloseParen" 
  | OpenParen  -> "OpenParen" 
  | Comma  -> "Comma" 
  | Disadvantage  -> "Disadvantage" 
  | Advantage  -> "Advantage" 
  | Max  -> "Max" 
  | Min  -> "Min" 
  | Dot  -> "Dot" 
  | Minus  -> "Minus" 
  | Plus  -> "Plus" 
  | DSymbol  -> "DSymbol" 
  | Number _ -> "Number" 
  | EOF  -> "EOF" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | String _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Ident _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Delete  -> (null : System.Object) 
  | Kill  -> (null : System.Object) 
  | Resolve  -> (null : System.Object) 
  | Declare  -> (null : System.Object) 
  | Sub  -> (null : System.Object) 
  | Add  -> (null : System.Object) 
  | Print  -> (null : System.Object) 
  | Set  -> (null : System.Object) 
  | Quit  -> (null : System.Object) 
  | QuestionMark  -> (null : System.Object) 
  | CloseParen  -> (null : System.Object) 
  | OpenParen  -> (null : System.Object) 
  | Comma  -> (null : System.Object) 
  | Disadvantage  -> (null : System.Object) 
  | Advantage  -> (null : System.Object) 
  | Max  -> (null : System.Object) 
  | Min  -> (null : System.Object) 
  | Dot  -> (null : System.Object) 
  | Minus  -> (null : System.Object) 
  | Plus  -> (null : System.Object) 
  | DSymbol  -> (null : System.Object) 
  | Number _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | EOF  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 1us; 65535us; 0us; 6us; 2us; 65535us; 20us; 21us; 36us; 37us; 1us; 65535us; 0us; 7us; 1us; 65535us; 0us; 4us; 2us; 65535us; 0us; 43us; 41us; 42us; 2us; 65535us; 0us; 44us; 41us; 44us; 3us; 65535us; 51us; 52us; 53us; 54us; 56us; 57us; 4us; 65535us; 0us; 50us; 41us; 50us; 59us; 60us; 61us; 62us; 7us; 65535us; 0us; 58us; 41us; 58us; 51us; 55us; 53us; 55us; 56us; 55us; 59us; 58us; 61us; 58us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 7us; 10us; 12us; 14us; 17us; 20us; 24us; 29us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 5us; 2us; 6us; 7us; 2us; 6us; 7us; 1us; 6us; 1us; 7us; 2us; 8us; 9us; 1us; 9us; 1us; 10us; 1us; 10us; 1us; 11us; 1us; 11us; 6us; 12us; 13us; 14us; 15us; 16us; 17us; 6us; 12us; 13us; 14us; 15us; 16us; 17us; 3us; 13us; 15us; 17us; 1us; 13us; 1us; 14us; 1us; 15us; 1us; 16us; 1us; 17us; 2us; 18us; 19us; 2us; 18us; 19us; 1us; 18us; 1us; 18us; 1us; 19us; 2us; 20us; 21us; 2us; 20us; 21us; 1us; 20us; 1us; 20us; 1us; 21us; 2us; 22us; 23us; 1us; 23us; 2us; 24us; 25us; 1us; 24us; 4us; 26us; 39us; 40us; 41us; 1us; 26us; 1us; 26us; 1us; 27us; 3us; 28us; 29us; 30us; 2us; 29us; 30us; 2us; 29us; 30us; 1us; 30us; 1us; 30us; 1us; 30us; 1us; 31us; 1us; 32us; 1us; 32us; 1us; 33us; 1us; 33us; 4us; 34us; 35us; 43us; 44us; 1us; 34us; 1us; 34us; 5us; 36us; 37us; 38us; 43us; 44us; 1us; 37us; 1us; 37us; 1us; 38us; 1us; 38us; 3us; 39us; 40us; 41us; 2us; 40us; 41us; 1us; 41us; 1us; 42us; 1us; 42us; 1us; 43us; 1us; 44us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 19us; 22us; 24us; 26us; 29us; 31us; 33us; 35us; 37us; 39us; 46us; 53us; 57us; 59us; 61us; 63us; 65us; 67us; 70us; 73us; 75us; 77us; 79us; 82us; 85us; 87us; 89us; 91us; 94us; 96us; 99us; 101us; 106us; 108us; 110us; 112us; 116us; 119us; 122us; 124us; 126us; 128us; 130us; 132us; 134us; 136us; 138us; 143us; 145us; 147us; 153us; 155us; 157us; 159us; 161us; 165us; 168us; 170us; 172us; 174us; 176us; |]
let _fsyacc_action_rows = 70
let _fsyacc_actionTableElements = [|13us; 32768us; 2us; 16us; 3us; 14us; 4us; 12us; 5us; 8us; 6us; 31us; 7us; 26us; 8us; 38us; 9us; 18us; 10us; 5us; 17us; 53us; 18us; 51us; 22us; 66us; 23us; 40us; 0us; 49152us; 1us; 32768us; 24us; 3us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 1us; 32768us; 1us; 9us; 2us; 32768us; 0us; 10us; 1us; 11us; 0us; 16390us; 0us; 16391us; 1us; 16392us; 1us; 13us; 0us; 16393us; 1us; 32768us; 1us; 15us; 0us; 16394us; 1us; 32768us; 1us; 17us; 0us; 16395us; 1us; 32768us; 1us; 19us; 3us; 16396us; 0us; 22us; 1us; 20us; 23us; 24us; 3us; 32768us; 0us; 23us; 1us; 36us; 23us; 25us; 0us; 16397us; 0us; 16398us; 0us; 16399us; 0us; 16400us; 0us; 16401us; 1us; 32768us; 1us; 27us; 2us; 32768us; 1us; 28us; 23us; 30us; 1us; 32768us; 23us; 29us; 0us; 16402us; 0us; 16403us; 1us; 32768us; 1us; 32us; 2us; 32768us; 1us; 33us; 23us; 35us; 1us; 32768us; 23us; 34us; 0us; 16404us; 0us; 16405us; 1us; 16406us; 1us; 36us; 0us; 16407us; 1us; 16409us; 1us; 39us; 0us; 16408us; 2us; 16423us; 19us; 41us; 22us; 64us; 4us; 32768us; 17us; 53us; 18us; 51us; 22us; 66us; 23us; 63us; 0us; 16410us; 0us; 16411us; 1us; 16412us; 11us; 45us; 1us; 32768us; 23us; 46us; 1us; 16413us; 13us; 47us; 1us; 32768us; 23us; 48us; 1us; 32768us; 12us; 49us; 0us; 16414us; 0us; 16415us; 2us; 32768us; 22us; 66us; 23us; 63us; 0us; 16416us; 2us; 32768us; 22us; 66us; 23us; 63us; 0us; 16417us; 3us; 16419us; 14us; 56us; 15us; 69us; 16us; 68us; 2us; 32768us; 22us; 66us; 23us; 63us; 0us; 16418us; 4us; 16420us; 15us; 69us; 16us; 68us; 20us; 61us; 21us; 59us; 2us; 32768us; 22us; 66us; 23us; 63us; 0us; 16421us; 2us; 32768us; 22us; 66us; 23us; 63us; 0us; 16422us; 1us; 16423us; 22us; 64us; 1us; 16424us; 23us; 65us; 0us; 16425us; 1us; 32768us; 23us; 67us; 0us; 16426us; 0us; 16427us; 0us; 16428us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 14us; 15us; 17us; 18us; 19us; 20us; 21us; 22us; 24us; 27us; 28us; 29us; 31us; 32us; 34us; 35us; 37us; 38us; 40us; 44us; 48us; 49us; 50us; 51us; 52us; 53us; 55us; 58us; 60us; 61us; 62us; 64us; 67us; 69us; 70us; 71us; 73us; 74us; 76us; 77us; 80us; 85us; 86us; 87us; 89us; 91us; 93us; 95us; 97us; 98us; 99us; 102us; 103us; 106us; 107us; 111us; 114us; 115us; 120us; 123us; 124us; 127us; 128us; 130us; 132us; 133us; 135us; 136us; 137us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 1us; 1us; 1us; 3us; 3us; 1us; 2us; 2us; 2us; 2us; 4us; 3us; 4us; 3us; 4us; 4us; 3us; 4us; 3us; 1us; 2us; 2us; 1us; 3us; 1us; 1us; 3us; 6us; 1us; 2us; 2us; 3us; 1us; 1us; 3us; 3us; 1us; 2us; 3us; 2us; 2us; 2us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 4us; 4us; 5us; 5us; 6us; 6us; 7us; 7us; 7us; 8us; 8us; 8us; 9us; 9us; 10us; 10us; 10us; 11us; 11us; 11us; 11us; 11us; 11us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 16387us; 16388us; 16389us; 65535us; 65535us; 16390us; 16391us; 65535us; 16393us; 65535us; 16394us; 65535us; 16395us; 65535us; 65535us; 65535us; 16397us; 16398us; 16399us; 16400us; 16401us; 65535us; 65535us; 65535us; 16402us; 16403us; 65535us; 65535us; 65535us; 16404us; 16405us; 65535us; 16407us; 65535us; 16408us; 65535us; 65535us; 16410us; 16411us; 65535us; 65535us; 65535us; 65535us; 65535us; 16414us; 16415us; 65535us; 16416us; 65535us; 16417us; 65535us; 65535us; 16418us; 65535us; 65535us; 16421us; 65535us; 16422us; 65535us; 65535us; 16425us; 65535us; 16426us; 16427us; 16428us; |]
let _fsyacc_reductions ()  =    [| 
# 265 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Statements.Command )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 274 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Command)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "Parser.fsy"
                                          _1 
                   )
# 45 "Parser.fsy"
                 :  Statements.Command ));
# 285 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'MultiRoll)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "Parser.fsy"
                                    Statements.RollCommand(_1) 
                   )
# 48 "Parser.fsy"
                 : 'Command));
# 296 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "Parser.fsy"
                               Statements.QuitCommand 
                   )
# 49 "Parser.fsy"
                 : 'Command));
# 306 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SetValue)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "Parser.fsy"
                                   _1 
                   )
# 50 "Parser.fsy"
                 : 'Command));
# 317 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'PrintValue)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "Parser.fsy"
                                     _1 
                   )
# 51 "Parser.fsy"
                 : 'Command));
# 328 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "Parser.fsy"
                                               Statements.SetValue(Some _2, "action", _3) 
                   )
# 52 "Parser.fsy"
                 : 'Command));
# 340 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "Parser.fsy"
                                              Statements.SetValue(Some _2, "action", _3) 
                   )
# 53 "Parser.fsy"
                 : 'Command));
# 352 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "Parser.fsy"
                                  Statements.ResolveAction(None) 
                   )
# 54 "Parser.fsy"
                 : 'Command));
# 362 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "Parser.fsy"
                                        Statements.ResolveAction(Some _2) 
                   )
# 55 "Parser.fsy"
                 : 'Command));
# 373 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "Parser.fsy"
                                     Statements.Delete(_2) 
                   )
# 56 "Parser.fsy"
                 : 'Command));
# 384 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "Parser.fsy"
                                       Statements.Delete(_2) 
                   )
# 57 "Parser.fsy"
                 : 'Command));
# 395 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "Parser.fsy"
                                    Statements.SetContext _2 
                   )
# 60 "Parser.fsy"
                 : 'SetValue));
# 406 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'Idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "Parser.fsy"
                                                 Statements.SetValue(Some _2, _3, _4) 
                   )
# 61 "Parser.fsy"
                 : 'SetValue));
# 419 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "Parser.fsy"
                                           Statements.SetValue(None, _2, _3) 
                   )
# 62 "Parser.fsy"
                 : 'SetValue));
# 431 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "Parser.fsy"
                                                 Statements.SetValue(Some _2, _3, _4) 
                   )
# 63 "Parser.fsy"
                 : 'SetValue));
# 444 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "Parser.fsy"
                                           Statements.SetValue(None, _2, _3.ToString()) 
                   )
# 64 "Parser.fsy"
                 : 'SetValue));
# 456 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "Parser.fsy"
                                                 Statements.SetValue(Some _2, _3, _4.ToString()) 
                   )
# 65 "Parser.fsy"
                 : 'SetValue));
# 469 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 66 "Parser.fsy"
                                                 Statements.AddValue(Some _2, _3, _4) 
                   )
# 66 "Parser.fsy"
                 : 'SetValue));
# 482 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "Parser.fsy"
                                           Statements.AddValue(None, _2, _3) 
                   )
# 67 "Parser.fsy"
                 : 'SetValue));
# 494 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "Parser.fsy"
                                                 Statements.AddValue(Some _2, _3, -_4) 
                   )
# 68 "Parser.fsy"
                 : 'SetValue));
# 507 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "Parser.fsy"
                                           Statements.AddValue(None, _2, -_3) 
                   )
# 69 "Parser.fsy"
                 : 'SetValue));
# 519 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 72 "Parser.fsy"
                                   _1 
                   )
# 72 "Parser.fsy"
                 : 'Idents));
# 530 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 73 "Parser.fsy"
                                        _1 + " " + _2 
                   )
# 73 "Parser.fsy"
                 : 'Idents));
# 542 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 76 "Parser.fsy"
                                      Statements.PrintValues (Some _2) 
                   )
# 76 "Parser.fsy"
                 : 'PrintValue));
# 553 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 77 "Parser.fsy"
                                Statements.PrintValues None 
                   )
# 77 "Parser.fsy"
                 : 'PrintValue));
# 563 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'MaybeTest)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 80 "Parser.fsy"
                                               Statements.Repeat(_1, _3) 
                   )
# 80 "Parser.fsy"
                 : 'MultiRoll));
# 575 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'MaybeTest)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 81 "Parser.fsy"
                                    _1 
                   )
# 81 "Parser.fsy"
                 : 'MultiRoll));
# 586 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Roll)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 84 "Parser.fsy"
                               Statements.Simple _1 
                   )
# 84 "Parser.fsy"
                 : 'MaybeTest));
# 597 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Roll)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "Parser.fsy"
                                                   Statements.AtLeast(Statements.Simple (_1), _3, 20) 
                   )
# 85 "Parser.fsy"
                 : 'MaybeTest));
# 609 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Roll)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 86 "Parser.fsy"
                                                                               Statements.AtLeast(Statements.Simple (_1), _3, _5) 
                   )
# 86 "Parser.fsy"
                 : 'MaybeTest));
# 622 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'PlusList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 89 "Parser.fsy"
                                   _1 
                   )
# 89 "Parser.fsy"
                 : 'Roll));
# 633 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'RollList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 90 "Parser.fsy"
                                       Statements.Min(_2) 
                   )
# 90 "Parser.fsy"
                 : 'Roll));
# 644 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'RollList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 91 "Parser.fsy"
                                       Statements.Max(_2) 
                   )
# 91 "Parser.fsy"
                 : 'Roll));
# 655 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'RollList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 94 "Parser.fsy"
                                                    List.append [_1] _3 
                   )
# 94 "Parser.fsy"
                 : 'RollList));
# 667 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 95 "Parser.fsy"
                                     [_1] 
                   )
# 95 "Parser.fsy"
                 : 'RollList));
# 678 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 98 "Parser.fsy"
                                     _1 
                   )
# 98 "Parser.fsy"
                 : 'PlusList));
# 689 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'PlusList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 99 "Parser.fsy"
                                                   Statements.MakeSum(_1, _3) 
                   )
# 99 "Parser.fsy"
                 : 'PlusList));
# 701 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'PlusList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 100 "Parser.fsy"
                                                    Statements.MakeSubtract(_1, _3) 
                   )
# 100 "Parser.fsy"
                 : 'PlusList));
# 713 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 103 "Parser.fsy"
                                      Statements.Roll(0, 0, _1) 
                   )
# 103 "Parser.fsy"
                 : 'SimpleRoll));
# 724 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 104 "Parser.fsy"
                                            Statements.Roll(_1, 6, 0) 
                   )
# 104 "Parser.fsy"
                 : 'SimpleRoll));
# 735 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 105 "Parser.fsy"
                                                  Statements.Roll(_1, _3, 0) 
                   )
# 105 "Parser.fsy"
                 : 'SimpleRoll));
# 747 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 106 "Parser.fsy"
                                                Statements.Roll(1, _2, 0) 
                   )
# 106 "Parser.fsy"
                 : 'SimpleRoll));
# 758 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 107 "Parser.fsy"
                                                   Statements.Max [_1; _1] 
                   )
# 107 "Parser.fsy"
                 : 'SimpleRoll));
# 769 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'SimpleRoll)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 108 "Parser.fsy"
                                                     Statements.Min [_1; _1] 
                   )
# 108 "Parser.fsy"
                 : 'SimpleRoll));
|]
# 781 "Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 28;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  Statements.Command  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
